#!/bin/bash
current_time=$(date "+%Y-%m-%d %H:%M:%S")
forge_pvp_pid=$(systemctl show --property MainPID --value forge-pvp.service)
function stop-server() {
  rm /run/forge_pvp_players_count
  echo "stopping server"
  systemctl stop forge-pvp.service forge-pvp.socket
  sleep 4s
  echo $current_time | xargs -I {} btrfs subvolume snapshot -r /srv/forge-pvp/ /srv/backup/forge-pvp/{}
  cd /srv/backup/forge-pvp
  ls -t | sed -n '6,$p' | xargs -I {} /usr/bin/btrfs subvolume delete {}
  sleep 1s
  systemctl start listen-fabric-survival.socket listen-forge-pvp.socket listen-vanilla-survival.socket
  systemctl stop stop-forge-pvp.timer
}

if [[ $forge_pvp_pid == 0 ]];
then
 stop-server
else
 current_players=$(ss -a | grep 12026 | grep  -o ESTAB | xargs)
 if [ -z $current_players ];
 then
  echo -n 0 >> /run/forge_pvp_players_count
 else
  echo -n "" > /run/forge_pvp_players_count
 fi
 idle_time=$(cat /run/forge_pvp_players_count)
 if [[ $idle_time == 000000000000000 ]];
 then
  stop-server
 fi
fi

