#!/bin/bash
current_time=$(date "+%Y-%m-%d %H:%M:%S")
fabric_survival_pid=$(systemctl show --property MainPID --value fabric-survival.service)
function stop-server() {
  rm /run/fabric_survival_players_count
  echo "stopping server"
  systemctl stop fabric-survival.service fabric-survival.socket
  sleep 4s
  echo $current_time | xargs -I {} btrfs subvolume snapshot -r /srv/fabric-survival/ /srv/backup/fabric-survival/{}
  cd /srv/backup/fabric-survival
  ls -t | sed -n '6,$p' | xargs -I {} /usr/bin/btrfs subvolume delete {}
  sleep 1s
  systemctl start listen-fabric-survival.socket listen-forge-pvp.socket listen-vanilla-survival.socket
  systemctl stop stop-fabric-survival.timer
}

if [[ $fabric_survival_pid == 0 ]];
then
 stop-server
else
 current_players=$(ss -a | grep 12024 | grep  -o ESTAB | xargs)
 if [ -z $current_players ];
 then
  echo -n 0 >> /run/fabric_survival_players_count
 else
  echo -n "" > /run/fabric_survival_players_count
 fi
 idle_time=$(cat /run/fabric_survival_players_count)
 if [[ $idle_time == 000000000000000 ]];
 then
  stop-server
 fi
fi

