#!/bin/bash
current_time=$(date "+%Y-%m-%d %H:%M:%S")
vanilla_survival_pid=$(systemctl show --property MainPID --value vanilla-survival.service)
function stop-server() {
  rm /run/vanilla_survival_players_count
  echo "stopping server"
  systemctl stop vanilla-survival.service vanilla-survival.socket
  sleep 4s
  echo $current_time | xargs -I {} btrfs subvolume snapshot -r /srv/vanilla-survival/ /srv/backup/vanilla-survival/{}
  cd /srv/backup/vanilla-survival
  ls -t | sed -n '6,$p' | xargs -I {} /usr/bin/btrfs subvolume delete {}
  sleep 1s
  systemctl start listen-fabric-survival.socket listen-forge-pvp.socket listen-vanilla-survival.socket
  systemctl stop stop-vanilla-survival.timer
}

if [[ $vanilla_survival_pid == 0 ]];
then
 stop-server
else
 current_players=$(ss -a | grep 12028 | grep  -o ESTAB | xargs)
 if [ -z $current_players ];
 then
  echo -n 0 >> /run/vanilla_survival_players_count
 else
  echo -n "" > /run/vanilla_survival_players_count
 fi
 idle_time=$(cat /run/vanilla_survival_players_count)
 if [[ $idle_time == 000000000000000 ]];
 then
  stop-server
 fi
fi

